### ISSUE TITLE
SensorModule error at "createKNXproduct"

### ISSUE THREAD

**Issue by Sonnengruesser** [OpenKNX/OpenKNXproducer#10]
I just downloaded KNX producer for the first time trying to get a [SensorModule-OneWire-1.5.2.zip](https://github.com/OpenKNX/OAM-SensorModule/releases/download/v1.5.2/SensorModule-OneWire-1.5.2.zip) up and running. 

When executing Build-knxprod.ps1 OpenKNXproducer crashes. So I just tried to use OpenKNXproducer directly with following result:
```

C:\Users\Christoph\Downloads\SensorModule>OpenKNXproducer.exe knxprod --NoXsd --Output="./test.knxprod" "data/content.xml"
OpenKNXproducer 2.16.0.0
Reading xml file data/content.xml writing to ./test.knxprod
Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at OpenKNXproducer.Program.FindEtsPath(String lXmlns)
   at OpenKNXproducer.Program.VerbKnxprod(KnxprodOptions opts)
   at OpenKNXproducer.Program.<>c.<Main>b__31_3(KnxprodOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at OpenKNXproducer.Program.Main(String[] args)
```
   
version 2.15.0.0 gives the same output.
ETS 5.7 works.

Was mach ich falsch?

**Comment by mumpf** [comment]
Hi, 

ich hab das eben auch versucht und konnte es nicht reproduzieren. Kannst Du noch was zu Deiner Systemumgebung sagen?
Win10 oder Win11?
ETS 6.1 oder 6.2?
Wie soll ich das mit ETS 5.7 works verstehen? Du hast ETS 6.x deinstalliert und dann läuft es?

**Comment by Sonnengruesser** [comment]
Sorry, das war wohl missverständlich...
Win10 und ETS 5.7 ist installiert (und in Verwendung hab ich gemeint). 
Installationspfad ist C:\Program Files (x86)\ETS5

**Comment by mumpf** [comment]
Hi,

ich hab mir das nochmal angeschaut. Es gibt nur einen einzigen Aufruf von Substring in der ganzen Methode, der kann nur schief gehen, wenn das zugrundeliegende xml-File corrupt ist. Du findest in Data-Verzeichnis eine Datei SensorModule.xml, kannst Du mir aus der Datei die ersten 5 Zeilen hier reinkopieren?

Danke!

**Comment by Sonnengruesser** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Content>
    <ETSapp Name="SensorModule" XmlFile="SensorModule.xml" />
    <Products>
        <Product Name="Sensormodul-v40-RP2040" Firmware="firmware-Sensormodul-v40-RP2040.uf2" Processor="RP2040" />
        <Product Name="SmartMF-1TE-RP2040" Firmware="firmware-SmartMF-1TE-RP2040.uf2" Processor="RP2040" />
        <Product Name="Sensormodul-v31-SAMD" Firmware="firmware-Sensormodul-v31-SAMD.bin" Processor="SAMD" />
        <Product Name="Sensormodul-v30-SAMD" Firmware="firmware-Sensormodul-v30-SAMD.bin" Processor="SAMD" />
    </Products>
</Content>

**Comment by mumpf** [comment]
Da hast Du mich missverstanden: Ich meinte SensorModule.xml (davon die ersten 5 Zeilen), Du hast mir die content.xml geschickt :-) 

Ich will nur verifizieren, dass das "richtige" auch bei Dir steht, und der Fehler deutet and falsche Werte innerhalb der ersten 5 Zeilen.

**Comment by Sonnengruesser** [comment]
Tja, kaum entpackt man das SensorModule.xml auch in den Ordner funktionierts... 
keine Ahnung warum das gefehlt hat 
Danke Waldemar für den Wink mit dem Zaunpfahl!
